analyzer:
  errors:
    depen ignored_on_referenced_packages: ignore
    depend_on_referenced_packages: ignore
include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
